// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import dotenv from "dotenv";
dotenv.config({ path: ".env", override: true });

import { defineConfig } from "prisma/config";

const url = process.env.DATABASE_URL;
if (!url) throw new Error("DATABASE_URL missing. Check your .env");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: { url: process.env.DATABASE_URL! },
});

